name: FAST-PT CI

on:
  push:
    branches:
      - beta-fpt
      - master
  pull_request:
    branches:
      - beta-fpt
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.13", "3.11", "3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install numpy==1.26.4
          pip install pytest

      - name: Run unit/benchmark tests
        run: pytest tests/
